[plotting]
[plotting.NPBDT]
run_title = "Runs 1-5"
[plotting.ZPBDT]
run_title = "Runs 1-5"
[plotting.NUMUCRTNP0PI]
run_title = "Runs 3-5"
[plotting.NUMUCRT0P0PI]
run_title = "Runs 3-5"
[plotting.TWOSHR]
run_title = "Runs 3-5"

[channels]
signal_channels = ["NPBDT", "ZPBDT"]
constraint_channels = ["NUMUCRTNP0PI", "NUMUCRT0P0PI", "TWOSHR"]

[[h0_params]]
name = "signal_strength"
value = 0.0

[[h1_params]]
name = "signal_strength"
value = 1.0

[fc_scan]
parameter_name = "signal_strength"
range = [0, 5]
n_points = 40

[[fc_scan.fit_grid]]
parameter = "signal_strength"
range = [0, 10]
n_points = 100

[uncertainty_defaults]
include_multisim_errors = true
add_ext_error_floor = false
use_sideband = true

# ------ Muon Sideband Generator ----- 
[[generator]]
[generator.load_runs]
run_numbers = ["3","4b","4c","4d","5"]
data = "muon_sideband"
truth_filtered_sets = ["nue", "drt"]
loadshowervariables = false
loadsystematics = true
use_bdt = false
loadnumuvariables = true
load_crt_vars = true
numupresel = true
enable_cache = true
blinded = false

[[generator.channel]]
variable = "neutrino_energy"
n_bins = 14
limits = [0.15, 1.55]
selection = "NUMUCRTNP0PI"
preselection = "NUMUCRT"
variable_tex = "Neutrino Reconstructed Energy (GeV)"

[[generator.channel]]
variable = "neutrino_energy"
n_bins = 14
limits = [0.15, 1.55]
selection = "NUMUCRT0P0PI"
preselection = "NUMUCRT"
variable_tex = "Neutrino Reconstructed Energy (GeV)"

# Adding the inclusive $\nu_\mu$ selection channel even though
# it is not used by default. This allows us to quickly compare
# the old and new selections without having to reload the entire
# analysis twice, by simply setting the `constraint_channels` 
# property at runtime.
[[generator.channel]]
variable = "neutrino_energy"
n_bins = 14
limits = [0.15, 1.55]
selection = "NUMUCRT"
preselection = "NUMUCRT"
variable_tex = "Neutrino Reconstructed Energy (GeV)"

# ------ Two-shower Sideband Generator ----- 
[[generator]]
[generator.load_runs]
run_numbers = ["3","4b","4c","4d","5"]
data = "two_shr_sideband"
truth_filtered_sets = ["nue", "drt"]
loadpi0variables = true
loadshowervariables = true
loadrecoveryvars = false
loadsystematics = true
load_crt_vars = true
load_lee = false
enable_cache = true
blinded = false

[[generator.channel]]
variable = "reco_e"
n_bins = 14
limits = [0.15, 1.55]
selection = "ZPLOOSESELTWOSHR"
preselection = "ZPTwoShrCRT"
label = "TWOSHR"
variable_tex = "Neutrino Reconstructed Energy (GeV)"


# ------- NUE Signal Generator -------
[[generator]]

mc_hist_generator_cls = "SignalOverBackgroundGenerator"

[generator.load_runs]
run_numbers = ["1", "2", "3","4b","4c","4d","5"]
data = "bnb"
truth_filtered_sets = ["nue", "drt"]
loadpi0variables = true
loadshowervariables = true
loadrecoveryvars = true
loadsystematics = true
load_lee = true
enable_cache = true
blinded = true

[[generator.parameter]]
name = "signal_strength"
value = 1.0
bounds = [0.0, 10.0]

[[generator.channel]]
variable = "reco_e"
n_bins = 10
limits = [0.15, 1.55]
selection = "NPBDT"
preselection = "NP"
variable_tex = "Reconstructed Energy (GeV)"

[[generator.channel]]
variable = "reco_e"
n_bins = 10
limits = [0.15, 1.55]
selection = "ZPBDT"
preselection = "ZP"
variable_tex = "Reconstructed Energy (GeV)"