[persistence]
output_dir = "../old_model_ana_ext_bin_range/"

[plotting]
[plotting.NPBDT]
run_title = "Runs 1-5"
[plotting.ZPBDT]
run_title = "Runs 1-5"
[plotting.NUMUCRTNP0PI]
run_title = "Runs 3-5"
[plotting.NUMUCRT0P0PI]
run_title = "Runs 3-5"
[plotting.TWOSHR]
run_title = "Runs 3-5"

[channels]
signal_channels = ["NPBDT", "ZPBDT"]
constraint_channels = ["NUMUCRTNP0PI", "NUMUCRT0P0PI", "TWOSHR"]

[[h0_params]]
name = "signal_strength"
value = 0.0

[[h1_params]]
name = "signal_strength"
value = 1.0

[fc_scan]
parameter_name = "signal_strength"
range = [0, 5]
n_points = 40

[[fc_scan.fit_grid]]
parameter = "signal_strength"
range = [0, 10]
n_points = 100

[uncertainty_defaults]
include_multisim_errors = true
add_ext_error_floor = false
use_sideband = true

# ------ Muon Sideband Generator ----- 
[[generator]]
[generator.load_runs]
run_numbers = ["3_crt", "4b", "4c", "4d","5"]
data = "bnb"
truth_filtered_sets = ["nue", "drt"]
loadshowervariables = false
loadsystematics = true
use_bdt = false
loadnumuvariables = true
load_crt_vars = true
numupresel = true
enable_cache = true
blinded = false

[generator.detvars]
# Only arguments that are to be overridden for detvars need to be 
# repeated here, otherwise all arguments from load_runs will be 
# copied over.
truth_filtered_sets = ["nue","nc_pi0"]

[[generator.channel]]
variable = "neutrino_energy"
n_bins = 14
limits = [0.15, 1.55]
selection = "NUMUCRTNP0PI"
preselection = "NUMUCRT"
variable_tex = "Reconstructed neutrino energy (GeV)"
variable_tex_short = "$E_{\\nu,\\mathrm{reco}}$"

[[generator.channel]]
variable = "neutrino_energy"
n_bins = 14
limits = [0.15, 1.55]
selection = "NUMUCRT0P0PI"
preselection = "NUMUCRT"
variable_tex = "Reconstructed neutrino energy (GeV)"
variable_tex_short = "$E_{\\nu,\\mathrm{reco}}$"

# Adding the inclusive $\nu_\mu$ selection channel even though
# it is not used by default. This allows us to quickly compare
# the old and new selections without having to reload the entire
# analysis twice, by simply setting the `constraint_channels` 
# property at runtime.
[[generator.channel]]
variable = "neutrino_energy"
n_bins = 14
limits = [0.15, 1.55]
selection = "NUMUCRT"
preselection = "NUMUCRT"
variable_tex = "Reconstructed neutrino energy (GeV)"
variable_tex_short = "$E_{\\nu,\\mathrm{reco}}$"

# ------ Two-shower Sideband Generator ----- 
[[generator]]
[generator.load_runs]
run_numbers = ["3_crt", "4b", "4c", "4d","5"]
data = "bnb"
truth_filtered_sets = ["nue", "drt"]
loadpi0variables = true
loadshowervariables = true
loadrecoveryvars = false
loadsystematics = true
load_crt_vars = true
load_lee = false
enable_cache = true
blinded = false

[generator.detvars]
# Only arguments that are to be overridden for detvars need to be 
# repeated here, otherwise all arguments from load_runs will be 
# copied over.
truth_filtered_sets = ["nue","nc_pi0"]

[[generator.channel]]
variable = "reco_e"
# n_bins = 10
# limits = [0.15, 1.0]
# Bin range extended to match other sideband channels. The oddly specific
# numbers come from matching the bin edges of the previous binning up to
# 1.0 GeV, and then extending the range to 1.595 GeV.
n_bins = 17
limits = [0.15, 1.595]
selection = "ZPLOOSESELTWOSHR"
preselection = "ZPTwoShrCRT"
label = "TWOSHR"
variable_tex = "Reconstructed neutrino energy (GeV)"
variable_tex_short = "$E_{\\mathrm{reco}}$"
selection_tex = "NC $\\pi^0$ sel."
selection_tex_short = "NC $\\pi^0$"


# ------- NUE Signal Generator -------
[[generator]]

mc_hist_generator_cls = "SignalOverBackgroundGenerator"

[generator.load_runs]
run_numbers = ["1", "2", "3_nocrt", "3_crt","4b","4c","4d","5"]
# run_numbers = ["4b","4c","4d","5"]
data = "bnb"
truth_filtered_sets = ["nue", "drt"]
loadpi0variables = true
loadshowervariables = true
loadrecoveryvars = true
loadsystematics = true
# For runs 1 and 2, the CRT variables will be automatically filled with dummy values
# that ensure that the CRT condition is always True.
load_crt_vars = true
load_lee = true
use_new_signal_model = false
enable_cache = true
blinded = false

[generator.detvars]
# Only arguments that are to be overridden for detvars need to be 
# repeated here, otherwise all arguments from load_runs will be 
# copied over.
truth_filtered_sets = ["nue","nc_pi0"]
# The full detvars are only calculated for this selection of events
extra_selection_query = "(mcf_pass_ncpi0 == 1 or (abs(nu_pdg) == 12 and ccnc == 0))"
# For the misc. background, we just add a flat fractional covariance
misc_background_query = "not (mcf_pass_ncpi0 == 1 or (abs(nu_pdg) == 12 and ccnc == 0))"
misc_background_error_frac = 0.2

[[generator.parameter]]
name = "signal_strength"
value = 1.0
bounds = [0.0, 10.0]

[[generator.channel]]
variable = "reco_e"
n_bins = 17
limits = [0.01, 2.39]
selection = "NPBDT"
preselection = "NP"
variable_tex = "Reconstructed neutrino energy (GeV)"
variable_tex_short = "$E_{\\mathrm{reco}}$"

[[generator.channel]]
variable = "reco_e"
n_bins = 17
limits = [0.01, 2.39]
# Adding CRT cuts to the ZP channel
selection = "ZPBDT_CRT"
preselection = "ZP"
label = "ZPBDT"
variable_tex = "Reconstructed neutrino energy (GeV)"
variable_tex_short = "$E_{\\mathrm{reco}}$"

[[generator.channel]]
variable = "reco_e"
n_bins = 17
limits = [0.01, 2.39]
selection = "ZPBDT"
preselection = "ZP"
label = "ZPBDT_NOCRT"
variable_tex = "Reconstructed neutrino energy (GeV)"
variable_tex_short = "$E_{\\mathrm{reco}}$"